import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
fig, ax = plt.subplots(figsize=(10, 6))
dark_blue="#1f3b73"; red="#b22222"; R=0.65
x1,x2,x3=1.5,5.0,8.5; yt=5.8; xb1,xb2=3.0,7.0; yb=1.8
ax.text(5.0,7.3,"OBSERVABLE EVENT (three elements)",ha="center",va="center",fontsize=13,fontweight="bold")
ax.text(5.0,3.4,"STATE (pair = value indefiniteness)",ha="center",va="center",fontsize=13,fontweight="bold")
ax.add_patch(Circle((x1,yt),R,fill=False,edgecolor=dark_blue,linewidth=2.0))
ax.text(x1,yt+0.12,"Initiator",ha="center",va="center",fontsize=10)
ax.text(x1,yt-0.18,"normal \u00b7 starts act",ha="center",va="center",fontsize=7)
ax.add_patch(Circle((x2,yt),R,fill=False,edgecolor=red,linewidth=2.0,linestyle="--"))
ax.text(x2,yt+0.12,"Quantum",ha="center",va="center",fontsize=10)
ax.text(x2,yt-0.18,"closed \u00b7 t \u2248 0",ha="center",va="center",fontsize=7)
ax.add_patch(Circle((x3,yt),R,fill=False,edgecolor=dark_blue,linewidth=2.0))
ax.text(x3,yt+0.12,"Receiver",ha="center",va="center",fontsize=10)
ax.text(x3,yt-0.18,"normal \u00b7 fills in answer",ha="center",va="center",fontsize=6.8)
ax.annotate("",xy=(x2-R,yt),xytext=(x1+R,yt),arrowprops=dict(arrowstyle="->",lw=1.5,color="black"))
ax.annotate("",xy=(x3-R,yt),xytext=(x2+R,yt),arrowprops=dict(arrowstyle="->",lw=1.5,color="black"))
ax.text(x3,yt-1.1,r"probably $\in (0,1)$",color=red,fontsize=9,style="italic",ha="center")
ax.add_patch(Circle((xb1,yb),R,fill=False,edgecolor=dark_blue,linewidth=2.0))
ax.text(xb1,yb+0.12,"Normal",ha="center",va="center",fontsize=10)
ax.text(xb1,yb-0.18,"definite property",ha="center",va="center",fontsize=7)
ax.add_patch(Circle((xb2,yb),R,fill=False,edgecolor=red,linewidth=2.0,linestyle="--"))
ax.text(xb2,yb+0.12,"Quantum",ha="center",va="center",fontsize=10)
ax.text(xb2,yb-0.18,"indefinite property",ha="center",va="center",fontsize=7)
ax.plot([xb1+R,xb2-R],[yb,yb],color="black",linewidth=1.5)
ax.text(5.0,0.45,"Kochen\u2013Specker: definite end \u21d2 indefinite end",fontsize=9,style="italic",ha="center")
ax.set_aspect("equal"); ax.set_xlim(0,10); ax.set_ylim(0,7.8); ax.axis("off")
plt.tight_layout()
plt.savefig("/mnt/user-data/outputs/fig_three_element_structure.pdf", bbox_inches="tight")
plt.savefig("/mnt/user-data/outputs/fig_three_element_structure.png", dpi=150, bbox_inches="tight")
print("fixed unicode")
